add verify step

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -22,7 +22,7 @@ jobs:
       - uses: actions/checkout@v4
         with:
           ref: ${{ env.BRANCH_NAME }}
-          
+
       - name: Remove .npmrc file if exists
         run: |
           if [ -f .npmrc ]; then
@@ -44,7 +44,14 @@ jobs:
         run: npm install -g @angular/cli
 
       - name: Install Node
-        run: npm install 
+        run: npm install
+        
+      - name: Verify angular.json exists
+        run: |
+          if [ ! -f angular.json ]; then
+            echo "angular.json file not found"
+            exit 1
+          fi
     
       - name: Lint
         run: npm run lint
